package com.laoyancheng.www.db.mapper;

import com.laoyancheng.www.db.domain.MarketCoupon;
import com.laoyancheng.www.db.domain.MarketCouponExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon
     *
     * @mbg.generated
     */
    long countByExample(MarketCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon
     *
     * @mbg.generated
     */
    int deleteByExample(MarketCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon
     *
     * @mbg.generated
     */
    int insert(MarketCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon
     *
     * @mbg.generated
     */
    int insertSelective(MarketCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon
     *
     * @mbg.generated
     */
    MarketCoupon selectOneByExample(MarketCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon
     *
     * @mbg.generated
     */
    MarketCoupon selectOneByExampleSelective(@Param("example") MarketCouponExample example, @Param("selective") MarketCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon
     *
     * @mbg.generated
     */
    List<MarketCoupon> selectByExampleSelective(@Param("example") MarketCouponExample example, @Param("selective") MarketCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon
     *
     * @mbg.generated
     */
    List<MarketCoupon> selectByExample(MarketCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon
     *
     * @mbg.generated
     */
    MarketCoupon selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MarketCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon
     *
     * @mbg.generated
     */
    MarketCoupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon
     *
     * @mbg.generated
     */
    MarketCoupon selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MarketCoupon record, @Param("example") MarketCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MarketCoupon record, @Param("example") MarketCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MarketCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MarketCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MarketCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}