package com.laoyancheng.www.db.mapper;

import com.laoyancheng.www.db.domain.MarketGoodsSpecification;
import com.laoyancheng.www.db.domain.MarketGoodsSpecificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketGoodsSpecificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_specification
     *
     * @mbg.generated
     */
    long countByExample(MarketGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_specification
     *
     * @mbg.generated
     */
    int deleteByExample(MarketGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_specification
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_specification
     *
     * @mbg.generated
     */
    int insert(MarketGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_specification
     *
     * @mbg.generated
     */
    int insertSelective(MarketGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_specification
     *
     * @mbg.generated
     */
    MarketGoodsSpecification selectOneByExample(MarketGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_specification
     *
     * @mbg.generated
     */
    MarketGoodsSpecification selectOneByExampleSelective(@Param("example") MarketGoodsSpecificationExample example, @Param("selective") MarketGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_specification
     *
     * @mbg.generated
     */
    List<MarketGoodsSpecification> selectByExampleSelective(@Param("example") MarketGoodsSpecificationExample example, @Param("selective") MarketGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_specification
     *
     * @mbg.generated
     */
    List<MarketGoodsSpecification> selectByExample(MarketGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_specification
     *
     * @mbg.generated
     */
    MarketGoodsSpecification selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MarketGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_specification
     *
     * @mbg.generated
     */
    MarketGoodsSpecification selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_specification
     *
     * @mbg.generated
     */
    MarketGoodsSpecification selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_specification
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MarketGoodsSpecification record, @Param("example") MarketGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_specification
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MarketGoodsSpecification record, @Param("example") MarketGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MarketGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MarketGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_specification
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MarketGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_specification
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}