package com.laoyancheng.www.db.mapper;

import com.laoyancheng.www.db.domain.MarketComment;
import com.laoyancheng.www.db.domain.MarketCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_comment
     *
     * @mbg.generated
     */
    long countByExample(MarketCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_comment
     *
     * @mbg.generated
     */
    int deleteByExample(MarketCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_comment
     *
     * @mbg.generated
     */
    int insert(MarketComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_comment
     *
     * @mbg.generated
     */
    int insertSelective(MarketComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_comment
     *
     * @mbg.generated
     */
    MarketComment selectOneByExample(MarketCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_comment
     *
     * @mbg.generated
     */
    MarketComment selectOneByExampleSelective(@Param("example") MarketCommentExample example, @Param("selective") MarketComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_comment
     *
     * @mbg.generated
     */
    List<MarketComment> selectByExampleSelective(@Param("example") MarketCommentExample example, @Param("selective") MarketComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_comment
     *
     * @mbg.generated
     */
    List<MarketComment> selectByExample(MarketCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_comment
     *
     * @mbg.generated
     */
    MarketComment selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MarketComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_comment
     *
     * @mbg.generated
     */
    MarketComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_comment
     *
     * @mbg.generated
     */
    MarketComment selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_comment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MarketComment record, @Param("example") MarketCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_comment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MarketComment record, @Param("example") MarketCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MarketComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MarketComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_comment
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MarketCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_comment
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}