package com.laoyancheng.www.db.mapper;

import com.laoyancheng.www.db.domain.MarketCategory;
import com.laoyancheng.www.db.domain.MarketCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_category
     *
     * @mbg.generated
     */
    long countByExample(MarketCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_category
     *
     * @mbg.generated
     */
    int deleteByExample(MarketCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_category
     *
     * @mbg.generated
     */
    int insert(MarketCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_category
     *
     * @mbg.generated
     */
    int insertSelective(MarketCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_category
     *
     * @mbg.generated
     */
    MarketCategory selectOneByExample(MarketCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_category
     *
     * @mbg.generated
     */
    MarketCategory selectOneByExampleSelective(@Param("example") MarketCategoryExample example, @Param("selective") MarketCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_category
     *
     * @mbg.generated
     */
    List<MarketCategory> selectByExampleSelective(@Param("example") MarketCategoryExample example, @Param("selective") MarketCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_category
     *
     * @mbg.generated
     */
    List<MarketCategory> selectByExample(MarketCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_category
     *
     * @mbg.generated
     */
    MarketCategory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MarketCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_category
     *
     * @mbg.generated
     */
    MarketCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_category
     *
     * @mbg.generated
     */
    MarketCategory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MarketCategory record, @Param("example") MarketCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MarketCategory record, @Param("example") MarketCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MarketCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MarketCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_category
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MarketCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_category
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}