package com.laoyancheng.www.db.mapper;

import com.laoyancheng.www.db.domain.MarketFeedback;
import com.laoyancheng.www.db.domain.MarketFeedbackExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketFeedbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_feedback
     *
     * @mbg.generated
     */
    long countByExample(MarketFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_feedback
     *
     * @mbg.generated
     */
    int deleteByExample(MarketFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_feedback
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_feedback
     *
     * @mbg.generated
     */
    int insert(MarketFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_feedback
     *
     * @mbg.generated
     */
    int insertSelective(MarketFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_feedback
     *
     * @mbg.generated
     */
    MarketFeedback selectOneByExample(MarketFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_feedback
     *
     * @mbg.generated
     */
    MarketFeedback selectOneByExampleSelective(@Param("example") MarketFeedbackExample example, @Param("selective") MarketFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_feedback
     *
     * @mbg.generated
     */
    List<MarketFeedback> selectByExampleSelective(@Param("example") MarketFeedbackExample example, @Param("selective") MarketFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_feedback
     *
     * @mbg.generated
     */
    List<MarketFeedback> selectByExample(MarketFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_feedback
     *
     * @mbg.generated
     */
    MarketFeedback selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MarketFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_feedback
     *
     * @mbg.generated
     */
    MarketFeedback selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_feedback
     *
     * @mbg.generated
     */
    MarketFeedback selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_feedback
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MarketFeedback record, @Param("example") MarketFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_feedback
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MarketFeedback record, @Param("example") MarketFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_feedback
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MarketFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_feedback
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MarketFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_feedback
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MarketFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_feedback
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}