package com.laoyancheng.www.db.mapper;

import com.laoyancheng.www.db.DTO.MarketBrandLabelDTO;
import com.laoyancheng.www.db.domain.MarketBrand;
import com.laoyancheng.www.db.domain.MarketBrandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_brand
     *
     * @mbg.generated
     */
    long countByExample(MarketBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_brand
     *
     * @mbg.generated
     */
    int deleteByExample(MarketBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_brand
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_brand
     *
     * @mbg.generated
     */
    int insert(MarketBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_brand
     *
     * @mbg.generated
     */
    int insertSelective(MarketBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_brand
     *
     * @mbg.generated
     */
    MarketBrand selectOneByExample(MarketBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_brand
     *
     * @mbg.generated
     */
    MarketBrand selectOneByExampleSelective(@Param("example") MarketBrandExample example, @Param("selective") MarketBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_brand
     *
     * @mbg.generated
     */
    List<MarketBrand> selectByExampleSelective(@Param("example") MarketBrandExample example, @Param("selective") MarketBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_brand
     *
     * @mbg.generated
     */
    List<MarketBrand> selectByExample(MarketBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_brand
     *
     * @mbg.generated
     */
    MarketBrand selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MarketBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_brand
     *
     * @mbg.generated
     */
    MarketBrand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_brand
     *
     * @mbg.generated
     */
    MarketBrand selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_brand
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MarketBrand record, @Param("example") MarketBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_brand
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MarketBrand record, @Param("example") MarketBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MarketBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MarketBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MarketBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);

    List<MarketBrandLabelDTO> selectBrandLabel();
}