package com.laoyancheng.www.db.mapper;

import com.laoyancheng.www.db.domain.MarketGoodsAttribute;
import com.laoyancheng.www.db.domain.MarketGoodsAttributeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketGoodsAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_attribute
     *
     * @mbg.generated
     */
    long countByExample(MarketGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_attribute
     *
     * @mbg.generated
     */
    int deleteByExample(MarketGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_attribute
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_attribute
     *
     * @mbg.generated
     */
    int insert(MarketGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_attribute
     *
     * @mbg.generated
     */
    int insertSelective(MarketGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_attribute
     *
     * @mbg.generated
     */
    MarketGoodsAttribute selectOneByExample(MarketGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_attribute
     *
     * @mbg.generated
     */
    MarketGoodsAttribute selectOneByExampleSelective(@Param("example") MarketGoodsAttributeExample example, @Param("selective") MarketGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_attribute
     *
     * @mbg.generated
     */
    List<MarketGoodsAttribute> selectByExampleSelective(@Param("example") MarketGoodsAttributeExample example, @Param("selective") MarketGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_attribute
     *
     * @mbg.generated
     */
    List<MarketGoodsAttribute> selectByExample(MarketGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_attribute
     *
     * @mbg.generated
     */
    MarketGoodsAttribute selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MarketGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_attribute
     *
     * @mbg.generated
     */
    MarketGoodsAttribute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_attribute
     *
     * @mbg.generated
     */
    MarketGoodsAttribute selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_attribute
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MarketGoodsAttribute record, @Param("example") MarketGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_attribute
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MarketGoodsAttribute record, @Param("example") MarketGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MarketGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MarketGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_attribute
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MarketGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_attribute
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}