package com.laoyancheng.www.db.mapper;

import com.laoyancheng.www.db.domain.MarketOrder;
import com.laoyancheng.www.db.domain.MarketOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order
     *
     * @mbg.generated
     */
    long countByExample(MarketOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order
     *
     * @mbg.generated
     */
    int deleteByExample(MarketOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order
     *
     * @mbg.generated
     */
    int insert(MarketOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order
     *
     * @mbg.generated
     */
    int insertSelective(MarketOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order
     *
     * @mbg.generated
     */
    MarketOrder selectOneByExample(MarketOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order
     *
     * @mbg.generated
     */
    MarketOrder selectOneByExampleSelective(@Param("example") MarketOrderExample example, @Param("selective") MarketOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order
     *
     * @mbg.generated
     */
    List<MarketOrder> selectByExampleSelective(@Param("example") MarketOrderExample example, @Param("selective") MarketOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order
     *
     * @mbg.generated
     */
    List<MarketOrder> selectByExample(MarketOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order
     *
     * @mbg.generated
     */
    MarketOrder selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MarketOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order
     *
     * @mbg.generated
     */
    MarketOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order
     *
     * @mbg.generated
     */
    MarketOrder selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MarketOrder record, @Param("example") MarketOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MarketOrder record, @Param("example") MarketOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MarketOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MarketOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MarketOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_order
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}