package com.laoyancheng.www.db.mapper;

import com.laoyancheng.www.db.domain.MarketUser;
import com.laoyancheng.www.db.domain.MarketUserExample;

import java.time.LocalDateTime;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user
     *
     * @mbg.generated
     */
    long countByExample(MarketUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user
     *
     * @mbg.generated
     */
    int deleteByExample(MarketUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user
     *
     * @mbg.generated
     */
    int insert(MarketUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user
     *
     * @mbg.generated
     */
    int insertSelective(MarketUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user
     *
     * @mbg.generated
     */
    MarketUser selectOneByExample(MarketUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user
     *
     * @mbg.generated
     */
    MarketUser selectOneByExampleSelective(@Param("example") MarketUserExample example, @Param("selective") MarketUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user
     *
     * @mbg.generated
     */
    List<MarketUser> selectByExampleSelective(@Param("example") MarketUserExample example, @Param("selective") MarketUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user
     *
     * @mbg.generated
     */
    List<MarketUser> selectByExample(MarketUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user
     *
     * @mbg.generated
     */
    MarketUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MarketUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user
     *
     * @mbg.generated
     */
    MarketUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user
     *
     * @mbg.generated
     */
    MarketUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MarketUser record, @Param("example") MarketUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MarketUser record, @Param("example") MarketUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MarketUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MarketUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MarketUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);

    List<MarketUser> selectUserListByAddTime(@Param("startTime") String startTime, @Param("endTime") String endTime);
}