package com.laoyancheng.www.db.mapper;

import com.laoyancheng.www.db.domain.MarketCollect;
import com.laoyancheng.www.db.domain.MarketCollectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketCollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_collect
     *
     * @mbg.generated
     */
    long countByExample(MarketCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_collect
     *
     * @mbg.generated
     */
    int deleteByExample(MarketCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_collect
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_collect
     *
     * @mbg.generated
     */
    int insert(MarketCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_collect
     *
     * @mbg.generated
     */
    int insertSelective(MarketCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_collect
     *
     * @mbg.generated
     */
    MarketCollect selectOneByExample(MarketCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_collect
     *
     * @mbg.generated
     */
    MarketCollect selectOneByExampleSelective(@Param("example") MarketCollectExample example, @Param("selective") MarketCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_collect
     *
     * @mbg.generated
     */
    List<MarketCollect> selectByExampleSelective(@Param("example") MarketCollectExample example, @Param("selective") MarketCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_collect
     *
     * @mbg.generated
     */
    List<MarketCollect> selectByExample(MarketCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_collect
     *
     * @mbg.generated
     */
    MarketCollect selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MarketCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_collect
     *
     * @mbg.generated
     */
    MarketCollect selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_collect
     *
     * @mbg.generated
     */
    MarketCollect selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_collect
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MarketCollect record, @Param("example") MarketCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_collect
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MarketCollect record, @Param("example") MarketCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MarketCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MarketCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_collect
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MarketCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_collect
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}