package com.laoyancheng.www.db.mapper;

import com.laoyancheng.www.db.domain.MarketSearchHistory;
import com.laoyancheng.www.db.domain.MarketSearchHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketSearchHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_search_history
     *
     * @mbg.generated
     */
    long countByExample(MarketSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_search_history
     *
     * @mbg.generated
     */
    int deleteByExample(MarketSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_search_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_search_history
     *
     * @mbg.generated
     */
    int insert(MarketSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_search_history
     *
     * @mbg.generated
     */
    int insertSelective(MarketSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_search_history
     *
     * @mbg.generated
     */
    MarketSearchHistory selectOneByExample(MarketSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_search_history
     *
     * @mbg.generated
     */
    MarketSearchHistory selectOneByExampleSelective(@Param("example") MarketSearchHistoryExample example, @Param("selective") MarketSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_search_history
     *
     * @mbg.generated
     */
    List<MarketSearchHistory> selectByExampleSelective(@Param("example") MarketSearchHistoryExample example, @Param("selective") MarketSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_search_history
     *
     * @mbg.generated
     */
    List<MarketSearchHistory> selectByExample(MarketSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_search_history
     *
     * @mbg.generated
     */
    MarketSearchHistory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MarketSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_search_history
     *
     * @mbg.generated
     */
    MarketSearchHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_search_history
     *
     * @mbg.generated
     */
    MarketSearchHistory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_search_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MarketSearchHistory record, @Param("example") MarketSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_search_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MarketSearchHistory record, @Param("example") MarketSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_search_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MarketSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_search_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MarketSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_search_history
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MarketSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_search_history
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}