package com.laoyancheng.www.db.mapper;

import com.laoyancheng.www.db.domain.MarketCouponUser;
import com.laoyancheng.www.db.domain.MarketCouponUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketCouponUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon_user
     *
     * @mbg.generated
     */
    long countByExample(MarketCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon_user
     *
     * @mbg.generated
     */
    int deleteByExample(MarketCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon_user
     *
     * @mbg.generated
     */
    int insert(MarketCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon_user
     *
     * @mbg.generated
     */
    int insertSelective(MarketCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon_user
     *
     * @mbg.generated
     */
    MarketCouponUser selectOneByExample(MarketCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon_user
     *
     * @mbg.generated
     */
    MarketCouponUser selectOneByExampleSelective(@Param("example") MarketCouponUserExample example, @Param("selective") MarketCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon_user
     *
     * @mbg.generated
     */
    List<MarketCouponUser> selectByExampleSelective(@Param("example") MarketCouponUserExample example, @Param("selective") MarketCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon_user
     *
     * @mbg.generated
     */
    List<MarketCouponUser> selectByExample(MarketCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon_user
     *
     * @mbg.generated
     */
    MarketCouponUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MarketCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon_user
     *
     * @mbg.generated
     */
    MarketCouponUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon_user
     *
     * @mbg.generated
     */
    MarketCouponUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MarketCouponUser record, @Param("example") MarketCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MarketCouponUser record, @Param("example") MarketCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MarketCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MarketCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon_user
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MarketCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_coupon_user
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}