package com.laoyancheng.www.db.mapper;

import com.laoyancheng.www.db.domain.MarketStorage;
import com.laoyancheng.www.db.domain.MarketStorageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_storage
     *
     * @mbg.generated
     */
    long countByExample(MarketStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_storage
     *
     * @mbg.generated
     */
    int deleteByExample(MarketStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_storage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_storage
     *
     * @mbg.generated
     */
    int insert(MarketStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_storage
     *
     * @mbg.generated
     */
    int insertSelective(MarketStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_storage
     *
     * @mbg.generated
     */
    MarketStorage selectOneByExample(MarketStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_storage
     *
     * @mbg.generated
     */
    MarketStorage selectOneByExampleSelective(@Param("example") MarketStorageExample example, @Param("selective") MarketStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_storage
     *
     * @mbg.generated
     */
    List<MarketStorage> selectByExampleSelective(@Param("example") MarketStorageExample example, @Param("selective") MarketStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_storage
     *
     * @mbg.generated
     */
    List<MarketStorage> selectByExample(MarketStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_storage
     *
     * @mbg.generated
     */
    MarketStorage selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MarketStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_storage
     *
     * @mbg.generated
     */
    MarketStorage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_storage
     *
     * @mbg.generated
     */
    MarketStorage selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_storage
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MarketStorage record, @Param("example") MarketStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_storage
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MarketStorage record, @Param("example") MarketStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MarketStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MarketStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_storage
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MarketStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_storage
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}