package com.laoyancheng.www.db.mapper;

import com.laoyancheng.www.db.domain.MarketAddress;
import com.laoyancheng.www.db.domain.MarketAddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_address
     *
     * @mbg.generated
     */
    long countByExample(MarketAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_address
     *
     * @mbg.generated
     */
    int deleteByExample(MarketAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_address
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_address
     *
     * @mbg.generated
     */
    int insert(MarketAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_address
     *
     * @mbg.generated
     */
    int insertSelective(MarketAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_address
     *
     * @mbg.generated
     */
    MarketAddress selectOneByExample(MarketAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_address
     *
     * @mbg.generated
     */
    MarketAddress selectOneByExampleSelective(@Param("example") MarketAddressExample example, @Param("selective") MarketAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_address
     *
     * @mbg.generated
     */
    List<MarketAddress> selectByExampleSelective(@Param("example") MarketAddressExample example, @Param("selective") MarketAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_address
     *
     * @mbg.generated
     */
    List<MarketAddress> selectByExample(MarketAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_address
     *
     * @mbg.generated
     */
    MarketAddress selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MarketAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_address
     *
     * @mbg.generated
     */
    MarketAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_address
     *
     * @mbg.generated
     */
    MarketAddress selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_address
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MarketAddress record, @Param("example") MarketAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_address
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MarketAddress record, @Param("example") MarketAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MarketAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MarketAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_address
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MarketAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_address
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}