package com.laoyancheng.www.db.mapper;

import com.laoyancheng.www.db.DTO.MarketRoleDTO;
import com.laoyancheng.www.db.domain.MarketRole;
import com.laoyancheng.www.db.domain.MarketRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_role
     *
     * @mbg.generated
     */
    long countByExample(MarketRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_role
     *
     * @mbg.generated
     */
    int deleteByExample(MarketRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_role
     *
     * @mbg.generated
     */
    int insert(MarketRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_role
     *
     * @mbg.generated
     */
    int insertSelective(MarketRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_role
     *
     * @mbg.generated
     */
    MarketRole selectOneByExample(MarketRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_role
     *
     * @mbg.generated
     */
    MarketRole selectOneByExampleSelective(@Param("example") MarketRoleExample example, @Param("selective") MarketRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_role
     *
     * @mbg.generated
     */
    List<MarketRole> selectByExampleSelective(@Param("example") MarketRoleExample example, @Param("selective") MarketRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_role
     *
     * @mbg.generated
     */
    List<MarketRole> selectByExample(MarketRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_role
     *
     * @mbg.generated
     */
    MarketRole selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MarketRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_role
     *
     * @mbg.generated
     */
    MarketRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_role
     *
     * @mbg.generated
     */
    MarketRole selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MarketRole record, @Param("example") MarketRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MarketRole record, @Param("example") MarketRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MarketRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MarketRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_role
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MarketRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_role
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);

    List<MarketRoleDTO> selectLabelList();
}