package com.laoyancheng.www.db.mapper;

import com.laoyancheng.www.db.domain.MarketNotice;
import com.laoyancheng.www.db.domain.MarketNoticeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_notice
     *
     * @mbg.generated
     */
    long countByExample(MarketNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_notice
     *
     * @mbg.generated
     */
    int deleteByExample(MarketNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_notice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_notice
     *
     * @mbg.generated
     */
    int insert(MarketNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_notice
     *
     * @mbg.generated
     */
    int insertSelective(MarketNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_notice
     *
     * @mbg.generated
     */
    MarketNotice selectOneByExample(MarketNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_notice
     *
     * @mbg.generated
     */
    MarketNotice selectOneByExampleSelective(@Param("example") MarketNoticeExample example, @Param("selective") MarketNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_notice
     *
     * @mbg.generated
     */
    List<MarketNotice> selectByExampleSelective(@Param("example") MarketNoticeExample example, @Param("selective") MarketNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_notice
     *
     * @mbg.generated
     */
    List<MarketNotice> selectByExample(MarketNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_notice
     *
     * @mbg.generated
     */
    MarketNotice selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MarketNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_notice
     *
     * @mbg.generated
     */
    MarketNotice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_notice
     *
     * @mbg.generated
     */
    MarketNotice selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_notice
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MarketNotice record, @Param("example") MarketNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_notice
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MarketNotice record, @Param("example") MarketNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MarketNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MarketNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_notice
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MarketNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_notice
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}