package com.laoyancheng.www.db.mapper;

import com.laoyancheng.www.db.domain.MarketAd;
import com.laoyancheng.www.db.domain.MarketAdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketAdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_ad
     *
     * @mbg.generated
     */
    long countByExample(MarketAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_ad
     *
     * @mbg.generated
     */
    int deleteByExample(MarketAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_ad
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_ad
     *
     * @mbg.generated
     */
    int insert(MarketAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_ad
     *
     * @mbg.generated
     */
    int insertSelective(MarketAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_ad
     *
     * @mbg.generated
     */
    MarketAd selectOneByExample(MarketAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_ad
     *
     * @mbg.generated
     */
    MarketAd selectOneByExampleSelective(@Param("example") MarketAdExample example, @Param("selective") MarketAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_ad
     *
     * @mbg.generated
     */
    List<MarketAd> selectByExampleSelective(@Param("example") MarketAdExample example, @Param("selective") MarketAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_ad
     *
     * @mbg.generated
     */
    List<MarketAd> selectByExample(MarketAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_ad
     *
     * @mbg.generated
     */
    MarketAd selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MarketAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_ad
     *
     * @mbg.generated
     */
    MarketAd selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_ad
     *
     * @mbg.generated
     */
    MarketAd selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_ad
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MarketAd record, @Param("example") MarketAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_ad
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MarketAd record, @Param("example") MarketAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_ad
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MarketAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_ad
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MarketAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_ad
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MarketAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_ad
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}