package com.laoyancheng.www.db.mapper;

import com.laoyancheng.www.db.domain.MarketGoodsProduct;
import com.laoyancheng.www.db.domain.MarketGoodsProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketGoodsProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_product
     *
     * @mbg.generated
     */
    long countByExample(MarketGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_product
     *
     * @mbg.generated
     */
    int deleteByExample(MarketGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_product
     *
     * @mbg.generated
     */
    int insert(MarketGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_product
     *
     * @mbg.generated
     */
    int insertSelective(MarketGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_product
     *
     * @mbg.generated
     */
    MarketGoodsProduct selectOneByExample(MarketGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_product
     *
     * @mbg.generated
     */
    MarketGoodsProduct selectOneByExampleSelective(@Param("example") MarketGoodsProductExample example, @Param("selective") MarketGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_product
     *
     * @mbg.generated
     */
    List<MarketGoodsProduct> selectByExampleSelective(@Param("example") MarketGoodsProductExample example, @Param("selective") MarketGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_product
     *
     * @mbg.generated
     */
    List<MarketGoodsProduct> selectByExample(MarketGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_product
     *
     * @mbg.generated
     */
    MarketGoodsProduct selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MarketGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_product
     *
     * @mbg.generated
     */
    MarketGoodsProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_product
     *
     * @mbg.generated
     */
    MarketGoodsProduct selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MarketGoodsProduct record, @Param("example") MarketGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MarketGoodsProduct record, @Param("example") MarketGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MarketGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MarketGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MarketGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}