package com.laoyancheng.www.db.mapper;

import com.laoyancheng.www.db.domain.MarketCart;
import com.laoyancheng.www.db.domain.MarketCartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_cart
     *
     * @mbg.generated
     */
    long countByExample(MarketCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_cart
     *
     * @mbg.generated
     */
    int deleteByExample(MarketCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_cart
     *
     * @mbg.generated
     */
    int insert(MarketCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_cart
     *
     * @mbg.generated
     */
    int insertSelective(MarketCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_cart
     *
     * @mbg.generated
     */
    MarketCart selectOneByExample(MarketCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_cart
     *
     * @mbg.generated
     */
    MarketCart selectOneByExampleSelective(@Param("example") MarketCartExample example, @Param("selective") MarketCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_cart
     *
     * @mbg.generated
     */
    List<MarketCart> selectByExampleSelective(@Param("example") MarketCartExample example, @Param("selective") MarketCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_cart
     *
     * @mbg.generated
     */
    List<MarketCart> selectByExample(MarketCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_cart
     *
     * @mbg.generated
     */
    MarketCart selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MarketCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_cart
     *
     * @mbg.generated
     */
    MarketCart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_cart
     *
     * @mbg.generated
     */
    MarketCart selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_cart
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MarketCart record, @Param("example") MarketCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_cart
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MarketCart record, @Param("example") MarketCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MarketCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MarketCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_cart
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MarketCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_cart
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}