package com.laoyancheng.www.db.mapper;

import com.laoyancheng.www.db.domain.MarketGoods;
import com.laoyancheng.www.db.domain.MarketGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated
     */
    long countByExample(MarketGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated
     */
    int deleteByExample(MarketGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated
     */
    int insert(MarketGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated
     */
    int insertSelective(MarketGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated
     */
    MarketGoods selectOneByExample(MarketGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated
     */
    MarketGoods selectOneByExampleSelective(@Param("example") MarketGoodsExample example, @Param("selective") MarketGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated
     */
    MarketGoods selectOneByExampleWithBLOBs(MarketGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated
     */
    List<MarketGoods> selectByExampleSelective(@Param("example") MarketGoodsExample example, @Param("selective") MarketGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated
     */
    List<MarketGoods> selectByExampleWithBLOBs(MarketGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated
     */
    List<MarketGoods> selectByExample(MarketGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated
     */
    MarketGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MarketGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated
     */
    MarketGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated
     */
    MarketGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MarketGoods record, @Param("example") MarketGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") MarketGoods record, @Param("example") MarketGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MarketGoods record, @Param("example") MarketGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MarketGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(MarketGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MarketGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MarketGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}